#
# MySQL
#
# Please visit reference below for more detail:
# - Run a Single-Instance Stateful Application#Deploy MySQL
# - https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  root.password: "123456"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306
      protocol: TCP
  type: NodePort
  selector:
    app: mysql
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: root.password
          ports:
            - containerPort: 3306
              name: mysql